# Matrices

## 5.1-  ¿Qué es una matriz?

Si A es una matriz $m × n$, esto es, una matriz con $m$ filas y $n$ columnas, entonces la entrada escalar en la i-ésima y la j-ésima columna de $A$ se denota mediante $a_{ij}$ y se llama entrada $(i, j)$ de A.<br><br>

<center>$
  M=
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1j}  \\
   a_{21} & a_{22}  & ... & a_{2j}  \\
   ... & ...  & ... & ...  \\
   a_{i1} & a_{i2}  & ... & a_{ij}  \\
  \end{array} } \right]
$</center><br><br>  

### Matriz diagonal
Una **matriz diagonal** es una matriz cuadrada que tiene todos los elementos $0$ excepto los elementos de su diagonal. Los elementos de la diagonal de una matriz cuadrada $A$ vienen definidos por: son $a_{11}, a_{22}, a_{33}...a_{nn}$
 
#### Matrices Identidad
Un ejemplo de **matrices diagonales** son las **matrices identidad**, las cuales son matrices cuadradas donde todos sus elementos son $0$ menos los elementos de la diagonal que son $1$.

Un ejemplo es la matriz identidad $I_{n}$ de dimensiones $n × n$ es:<br><br>

<center>$
  I_n=
  \left[ {\begin{array}{cc}
   1 & 0  & ... & 0  \\
   0 & 1  & ... & 0  \\
   ... & ...  & ... & ...  \\
   0 & 0  & ... & 1  \\
  \end{array} } \right]
$</center><br><br>

<div class="alert alert-success">
    <b>No debemos temer a la matriz identidad, la matriz identidad es nuestra amiga ✌️. Debemos pensar en la matriz identidad como si fuera el número 1. Por ejemplo:</b>
</div>

- Cuando multiplicamos el número $1$ por otro número $x$ obtenemos el mismo número $x$ - **NEUTRALIDAD**:<br><br>
<center>$1\cdot4 = 4$</center><br>

- Si calculamos el inverso de $1$, obtenemos $1$ de nuevo - **INVERSIBLE**:<br><br>
<center>$1^{-1}= 1$</center><br>

- Al elevar $1$ a otro número $X$, siempre nos quedará $1$ - **IDEMPOTENCIA**:<br><br>
<center>$1^{5}= 1$</center><br>

Si en vez de usar el número $1$ usamos una **matriz identidad** $I_{n}$, ¿qué sucede?:

- Cuando multiplicamos una matriz identidad $I_{n}$ por otra matriz $A$ obtendremos la misma matriz $A$ - **NEUTRALIDAD - PRODUCTO NEUTRO**:<br><br>
<center>$A\cdot I_{n} = A$</center><br>

- El inverso de la matriz identidad $I_{n}$ es la matriz identidad $I_{n}$ de nuevo - **INVERSIBLE**:<br><br>
<center>$I_{n}^{-1}= I_{n}$</center><br>

- La matriz identidad $I_{n}$ elevada a otra valor $X$, siempre nos quedará la matriz identidad $I_{n}$ - **IDEMPOTENCIA**:<br><br>
<center>$I_{n}^{5}= I_{n}$</center><br>


### Matriz triangular

Una **matriz triangular** es una matriz cuadrada la cual tiene triángulos de ceros por encima o por debajo de la diagonal. En caso de que los valores ceros estén por encima de la diagonal se denomina **matriz triangular superior** y si es por debajo de la diagonal se denomina como **matriz triangular inferior**.<br><br>

**Matriz triangular inferior**:

<center>$
  U_{nxm}=
  \left[ {\begin{array}{cc}
   1 & 4  & 6  \\
   0 & 2  & 2  \\
   0 & 0  & 1  \\
  \end{array} } \right]
$</center><br><br>

**Matriz triangular superior**:

<center>$
  U_{nxm}=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 \\
   4 & 2  & 0\\
   7 & 3  & 1  \\
  \end{array} } \right]
$</center><br><br>

## 5.2-  Matrices en Python

### 5.2.1- Usando Listas
Python no tiene incorporado internamente matrices __'per se'__. Sin embargo, podemos tratar a una lista como una matriz. Por ejemplo:

In [2]:
A = [[1, 4, 5], [-5, 8, 9]]

print(A)
print(type(A))

[[1, 4, 5], [-5, 8, 9]]
<class 'list'>


Al ser una lista no podemos imprimir su tamaño, pero sí su longitud:

In [3]:
print(len(A))
print(A.shape)

2


AttributeError: 'list' object has no attribute 'shape'

Al ser una lista, podemos acceder a sus elementos como ya vimos:

<div class="alert alert-block alert-danger">
    <b>⚠️ ATENCIÓN ⚠️</b> Los índices empiezan en 0!!
</div>

In [4]:
A[0]

[1, 4, 5]

Si quisieramos obtener la 3 columna, deberíamos hacer:

In [5]:
A

[[1, 4, 5], [-5, 8, 9]]

In [6]:
col = []
for row in A:
    col.append(row[2])
    
col

[5, 9]

Podemos utilizar las listas para operaciones con matrices cuando sea algo sencillo y que no requiera operaciones muy complejas. Pero para el resto lo mejor es usar **Numpy**.

### 5.2.2- Usando Numpy

En **Numpy** podemos crear una matriz tanto usando la funcion `np.matrix()` como `np.array()`. Sin embargo, es totalmente desaconsejable usar `np.matrix()` ya que en la propia documentación de **Numpy** nos advierten de que dicha clase puede ser eliminada en cualquier momento.

<div class="alert alert-block alert-danger">
    <b>⚠️ NOTE ⚠️</b> It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future. Check it <a href=https://numpy.org/devdocs/reference/generated/numpy.matrix.html?highlight=matrix#numpy.matrix>Here.</a>
</div>

Por tanto, nosotros vamos a usar `np.array()`. Para crear una matriz simplemento debemos definir:

In [8]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
A.shape

(2, 3)

Podemos generar la **matriz identidad** usando `np.identity()`

In [12]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.identity(1)

array([[1.]])

Para crear una matriz donde todos sus elementos sean 0 excepto la diagonal podemos usar `np.eye`

In [19]:
C = np.eye(4, 3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [20]:
C.shape

(4, 3)

También podemos controlar que diagonal se rellena

In [21]:
C = np.eye(4, 3, k=-1)
C

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(4, 4) # == np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Para generar una matriz llena de ceros

In [24]:
A = np.zeros((4, 6))
A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## 5.3- Suma de matrices

* Se dice que dos **matrices** son **iguales** si tienen el mismo tamaño, es decir, el mismo número de filas y de columnas, y sus columnas correspondientes son iguales.  
* Si A y B son matrices m × n, entonces la suma A + B es la matriz m × n cuyas columnas son las sumas de las columnas correspondientes de A y B.
* La suma A + B está definida sólo cuando A y B son del mismo tamaño.  

<div class="alert alert-success">
    <b>Queremos sumar estas dos matrices:</b>

<center>$m_1=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$</center><br>

<center>$
  m_2=
  \left[ {\begin{array}{cc}
   -1 & 2 \\
   1 & -2\\
  \end{array} } \right]
$</center>
</div>

In [25]:
m1 = np.array([[1, 4], [2, 0]])
m2 = np.array([[-1, 2], [1, -2]])

m1 + m2

array([[ 0,  6],
       [ 3, -2]])

En caso de que tuvieran distinto tamaño:

In [26]:
m3 = np.eye(4, 3)
m3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [27]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,2) (4,3) 

## 5.4- Multiplicación de una matriz por un escalar

* Si r es un escalar y A es una matriz, entonces el múltiplo escalar rA es la matriz cuyas columnas son r veces las columnas correspondientes de A. 
* Al igual que con los vectores, se define −A como (−1)A y se escribe A − B en lugar de A + (−1)B.

<div class="alert alert-success">
    <b>Multiplicar por 2 la siguiente matriz:</b>

<center>$
A_{1}=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$</center>
</div>

In [28]:
a = 2

A1 = np.array([[1, 4], [2, 0]])
a*A1

array([[2, 8],
       [4, 0]])

## 5.5- Multiplicación matricial

Si $A$ es una matriz $m × n$, y si $B$ es una matriz $n × p$ con columnas $b_1, b_2,... b_p$, entonces el **producto AB** es la matriz $m × p$ cuyas columnas son:<br><br>

<center>A*B= $
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1n}  \\
   a_{21} & a_{22}  & ... & a_{2n}  \\
   ... & ...  & ... & ...  \\
   a_{m1} & a_{m2}  & ... & a_{mn}  \\
  \end{array} } \right]
$ * $
  \left[ {\begin{array}{cc}
   b_{11} & b_{12}  & ... & b_{1p}  \\
   b_{21} & b_{22}  & ... & b_{2p}  \\
   ... & ...  & ... & ...  \\
   b_{n1} & b_{n2}  & ... & b_{np}  \\
  \end{array} } \right]
$ =<br><br> $
  \left[ {\begin{array}{cc}
   a_{11}\cdot b_{11}+ a_{12}\cdot b_{21} + ... + a_{1n}\cdot b_{n1}& a_{11}\cdot b_{12}+ a_{12}\cdot b_{22} + ... + a_{1n}\cdot b_{n2}  & ... & a_{11}\cdot b_{1p}+ a_{12}\cdot b_{2p} + ... + a_{1n}\cdot b_{np}  \\
   a_{21}\cdot b_{11}+ a_{22}\cdot b_{21} + ... + a_{2n}\cdot b_{n1}& a_{21}\cdot b_{12}+ a_{22}\cdot b_{22} + ... + a_{2n}\cdot b_{n2}  & ... & a_{21}\cdot b_{1p}+ a_{22}\cdot b_{2p} + ... + a_{2n}\cdot b_{np}  \\
   ... & ...  & ... & ...  \\
      a_{m1}\cdot b_{11}+ a_{m2}\cdot b_{21} + ... + a_{mn}\cdot b_{n1}& a_{m1}\cdot b_{12}+ a_{m2}\cdot b_{22} + ... + a_{mn}\cdot b_{n2}  & ... & a_{m1}\cdot b_{1p}+ a_{m2}\cdot b_{2p} + ... + a_{mn}\cdot b_{np}  \\
  \end{array} } \right]
$  
</center>

<div class="alert alert-success">
    <b>Multiplicar las siguientes matrices:</b>

<center>
$A_{1}=
  \left[ {\begin{array}{cc}
   1 & 4 \\
   2 & 0\\
  \end{array} } \right]
$</center><br>
<center>$
  A_{2}=
  \left[ {\begin{array}{cc}
   -1 & 2 \\
   1 & -2\\
  \end{array} } \right]
$</center>

In [29]:
A1 = np.array([[1, 4], [2, 0]])
A2 = np.array([[-1, 2], [1, -2]])

print(A1.shape)
print(A2.shape)

(2, 2)
(2, 2)


In [30]:
A1 * A2

array([[-1,  8],
       [ 2,  0]])

¿Es raro, no? No es el resultado que esperamos al hacer la multiplicación matricial de estas matrices...¿no? El resultado debería ser algo así:<br><br>

<center>$result =\left[ {\begin{array}{cc}
   3 & -6 \\
   -2 & 4\\
  \end{array} } \right]
$</center><br>

**¿Por qué?...**

<img src="./Images/matriz.jpg" align="left" width=60%>

Esto se debe a que **Numpy** está multiplicando elemento por elemento, si queremos realizar la **multiplicación matricial** tenemos que usar `np.dot()`

In [ ]:
# np.dot(v1, v2)
# v1 @ v2

In [32]:
np.dot(A1, A2)

array([[ 3, -6],
       [-2,  4]])

<div class="alert alert-block alert-danger">
    <b>⚠️ ATENCIÓN ⚠️</b>  En general, AB ≠ BA. 
</div>

<div class="alert alert-success">
    <b>Realiza la multiplicación de AB y BA de las siguientes matrices:</b>

<center>
$A=
  \left[ {\begin{array}{cc}
   5 & 1 \\
   3 & -2\\
  \end{array} } \right]
$</center><br>
<center>$
  B=
  \left[ {\begin{array}{cc}
   2 & 0 \\
   4 & 3\\
  \end{array} } \right]
$</center>
</div>

In [33]:
A = np.array([[5, 1], 
              [3, -2]])

B = np.array([[2, 0],
              [4, 3]])

AB = np.dot(A, B)
print(AB)

[[14  3]
 [-2 -6]]


In [34]:
BA = np.dot(B, A)
print(BA)

[[10  2]
 [29 -2]]


<div class="alert alert-success">
    <b>Dada las siguientes matrices A,B y C, comprueba si AB es igual a AC.</b>

<center>
$
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$</center><br>
<center>$
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$</center><br>
<center>$
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$</center>

In [35]:
A = np.array([[2, -3],
              [-4, 6]])

B = np.array([[8, 4],
              [5, 5]])

C = np.array([[5, -2],
              [3, 1]])

#AB = np.dot(A, B)
AB = A.dot(B)
AC = A.dot(C)

Podemos usar `np.array_equal()` para comprobar si dos arrays son iguales

In [36]:
np.array_equal(AB, AC)

True

In [37]:
AB

array([[ 1, -7],
       [-2, 14]])

In [38]:
AC

array([[ 1, -7],
       [-2, 14]])

In [43]:
np.all((AB == AC)) # if all():

True

## 5.6- Matriz transpuesta / traspuesta

Dada una matriz $A$ de $m × n$, la transpuesta de $A$ es la matriz $n × m$, denotada mediante $A^T$, cuyas columnas se forman a partir de las filas correspondientes de $A$. En resumen, la **matriz transpuesta** es aquella que se obtiene al transformar las filas en columnas y las columnas en filas, del siguiente modo:


<center>$A=
  \left[ {\begin{array}{cc}
   5 & 1 & 7\\
   3 & -2 & 5\\
  \end{array} } \right]
$ , su matriz traspuesta es $
  A^T=
  \left[ {\begin{array}{cc}
   5 & 3 \\
   1 & -2\\
   7 & 5\\
  \end{array} } \right]
$.</center>

Usamos `np.transpose()` para calcular la transpuesta de una matriz $A$: 

In [47]:
A = np.array([[5, 1, 7], [3, -2, 5]])

At = np.transpose(A)
At

array([[ 5,  3],
       [ 1, -2],
       [ 7,  5]])

¿Qué sucede si volvemos a realizar la transpuesta?

In [48]:
np.transpose(At)

array([[ 5,  1,  7],
       [ 3, -2,  5]])

Obtenemos de nuevo la matriz $A$

#### Matriz Cuadrada

Una **matriz cuadrada** va a ser simétrica si $A^T=A$, es decir si $A$ es igual a su propia matriz transpuesta. Por ejemplo:

In [49]:
C = np.array([[126, -66, 88],
              [-66, 58, -50],
              [88, -50, 46]])

Ct = np.transpose(C)
Ct

array([[126, -66,  88],
       [-66,  58, -50],
       [ 88, -50,  46]])

In [50]:
np.array_equal(C, Ct)

True

## 5.7- Matriz inversa (usando Gauss)

Al igual que el inverso de 5 es $\frac{1}{5} = 5^{-1}$, dada la matriz $A$, no puedo calcular $\frac{1}{A}$, pero sí $A^{-1}$.

La manera usual de calcular la **matriz inversa**, sobre todo si no es demasiado grande, es mediante determinantes (lo veremos posteriormente), pero hay otro modo general de calcular la matriz inversa, que es con el método de Gauss:  
* Dada una matriz $A$, considero la matriz $(A|I)$
* Mediante una serie de transformaciones tengo que conseguir transformarla en $(I|B)$
* $B = A^{-1}$  

<div class="alert alert-success">
    <b>Vamos a calcular la inversa de la siguiente matriz $A$ usando el método de Gauss:</b><br><br>

<center>$
   A= \left[ {\begin{array}{cc}
   0 & 1 & 2\\
   1 & 0 & 3\\
   4 & -3 & 8\\
  \end{array} } \right]
$</center>
</div>

Lo primero que vamos a hacer es añadir a la derecha de la matriz $A$ una matriz identidad y obtendremos $(A|I)$:<br><br>
    
<center>$
  (A|I)=
  \left[ {\begin{array}{cc}
   0 & 1 & 2 & 1 & 0 & 0\\
   1 & 0 & 3 & 0 & 1 & 0\\
   4 & -3 & 8 & 0 & 0 & 1\\
  \end{array} } \right]
$</center>

In [51]:
AI = np.array([[0, 1, 2, 1, 0, 0],
               [1, 0, 3, 0, 1, 0],
               [4, -3, 8, 0, 0, 1]])

AI

array([[ 0,  1,  2,  1,  0,  0],
       [ 1,  0,  3,  0,  1,  0],
       [ 4, -3,  8,  0,  0,  1]])

Buscamos hacer transformaciones de modo que obtengamos una matriz con la forma $(I|B)$, donde $B$ será la inversa de $A$. Lo primero que hacemos es intercambiar la segunda fila con la primera fila.

<center>
$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 3 & 0 & 1 & 0\\
   0 & 1 & 2 & 1 & 0 & 0\\
   4 & -3 & 8 & 0 & 0 & 1\\
  \end{array} } \right]$
</center>

In [52]:
AI = np.array([AI[1], AI[0], AI[2]])
AI

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 4, -3,  8,  0,  0,  1]])

Queremos hacer $0$ el primer elemento de la 3ª fila. Para ello, la tercera fila se convertirá en el resultado de multiplicar -4 por la primera fila y sumarle la 3ª fila.

<center>3ª fila = -4 * (1ª fila) + (3ª fila)</center><br><br>

<center>$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 3 & 0 & 1 & 0\\
   0 & 1 & 2 & 1 & 0 & 0\\
   0 & -3 & -4 & 0 & -4 & 1\\
  \end{array} } \right]
$ </center> 

In [53]:
AI = np.array([AI[0], AI[1], (-4*AI[0] + AI[2])])
AI

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 0, -3, -4,  0, -4,  1]])

Seguidamente, queremos hacer $0$ el segundo elemento de la tercera fila, para ello haremos:<br><br>

<center>3ª fila = 3 * (2ª fila) + (3ª fila)</center><br>

<center>$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 3 & 0 & 1 & 0\\
   0 & 1 & 2 & 1 & 0 & 0\\
   0 & 0 & 2 & 3 & -4 & 1\\
  \end{array} } \right]
$</center> 

In [54]:
AI_ = np.array([AI[0], AI[1], (3*AI[1] + AI[2])])
AI_

array([[ 1,  0,  3,  0,  1,  0],
       [ 0,  1,  2,  1,  0,  0],
       [ 0,  0,  2,  3, -4,  1]])

El siguiente paso es hacer 0 el 3º elemento de la primera fila, para ello haremos:<br><br>

<center>1ª fila = (1ª fila) - 3/2 * (3ª fila)</center><br>

<center>$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & -9/2 & 7 & -3/2\\
   0 & 1 & 2 & 1 & 0 & 0\\
   0 & 0 & 2 & 3 & -4 & 1\\
  \end{array} } \right]
$</center> 

In [55]:
AI_ = np.array([(AI_[0] - 3/2*AI_[2]),
               AI_[1],
               AI_[2]])
AI_

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  2. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  2. ,  3. , -4. ,  1. ]])

Ya queda menos! El siguiente paso es hacer 0 el tercer elemento de la segunda fila, para ello haremos:<br><br>

<center>2ª fila = (2ª fila) - (3ª fila)</center><br>

<center>$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & -9/2 & 7 & -3/2\\
   0 & 1 & 0 & -2 & 4 & -1\\
   0 & 0 & 2 & 3 & -4 & 1\\
  \end{array} } \right]
$</center> 

In [56]:
AI_ = np.array([AI_[0], (AI_[1] - AI_[2]), AI_[2]])
AI_

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  2. ,  3. , -4. ,  1. ]])

Debemos hacer 1 el 3º elemento de la última fila. Para ello:<br><br>

<center>(3ª fila) = (1/2) * (3ª fila)</center><br>

<center>$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & -9/2 & 7 & -3/2\\
   0 & 1 & 0 & -2 & 4 & -1\\
   0 & 0 & 1 & 3/2 & -2 & 1/2\\
  \end{array} } \right]
$</center> 

In [57]:
AI_ = np.array([AI_[0],
                AI_[1],
                (AI_[2]*1/2)])

AI_

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

Por tanto, después de todo este proceso, la matriz inversa queda:</style> 

<center>$
  (A|I)=
  \left[ {\begin{array}{cc}
   1 & 0 & 0 & -9/2 & 7 & -3/2\\
   0 & 1 & 0 & -2 & 4 & -1\\
   0 & 0 & 1 & 3/2 & -2 & 1/2\\
  \end{array} } \right]
$</center> 

Es decir $A^{-1}$:

<center>$
  A^{-1}=
  \left[ {\begin{array}{cc}
   -9/2 & 7 & -3/2\\
   -2 & 4 & -1\\
   3/2 & -2 & 1/2\\
  \end{array} } \right]
$</center>

<img src="./Images/tired.gif" width=20%>

Menos mal que existe **Python** y **Numpy** para poder hacer todo esto de una manera mucho más rápida. Aunque las bases siempre hay que entenderlas porque es lo que nos va a diferenciar del resto! ✌️

In [58]:
A = np.array([[0, 1, 2],
              [1, 0, 3],
              [4, -3, 8]])

inv_A = np.linalg.inv(A)
inv_A

array([[-4.5,  7. , -1.5],
       [-2. ,  4. , -1. ],
       [ 1.5, -2. ,  0.5]])

In [59]:
A.dot(inv_A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5.8- Rango de una matriz

Los números de columnas $m$ y filas $n$ pueden darnos el tamaño de una matriz, pero esto no necesariamente representa el verdadero tamaño del sistema lineal, ya que por ejemplo si existen **dos filas iguales** en una matriz $A$, la segunda fila desaparecía en el proceso de eliminación.

Por tanto, el verdadero tamaño de la matriz $A$ va a estar definido por su **rango**. El **rango** de una matriz es el número máximo de columnas y filas que son linealmente independientes. Por ejemplo:

<center>$
  A = 
  \left[ {\begin{array}{cc}
   1 & 1 & 2 & 4\\
   1 & 2 & 2 & 5\\
   1 & 3 & 2 & 6\\
  \end{array} } \right]
$</center><br><br>

Podemos ver que la tercer columna $[2, 2, 2]$ es múltiplo de la primera y que la cuarta columna $[4, 5, 6]$ es la suma de las primeras 3 columnas. Por tanto **el rango de A va a ser igual a 2**; ya que la tercer y cuarta columna pueden ser eliminadas.

In [60]:
A = np.array([[1, 1, 2, 4],
              [1, 2, 2, 5],
              [1, 3, 2, 6]])

np.linalg.matrix_rank(A)

2

## 5.9- Factorización LU (Lower-Upper)

Sea $A$ una matriz tenemos:  
 
<center>$A = LU$</center>

donde $L$ y $U$ son matrices inferiores y superiores triangulares respectivamente.  

Si pensamos en una matriz cuadrada:<br><br>
$
  \left[ {\begin{array}{cc}
   a_{11} & a_{12}  & ... & a_{1n}  \\
   a_{21} & a_{22}  & ... & a_{2n}  \\
   ... & ...  & ... & ...  \\
   a_{n1} & a_{n2}  & ... & a_{nn}  \\
  \end{array} } \right]
$ =
$
  \left[ {\begin{array}{cc}
   1      & 0       & 0    & ... & 0  \\
   l_{21} & 1       & 0    & ... & 0  \\
   ...    & ...     & ...  & ... & ... \\
   l_{n1} & l_{n2}  & ...  & ... & 1  \\
  \end{array} } \right]
$* $
  \left[ {\begin{array}{cc}
   u_{11} & u_{12} & u_{13} & ... & u_{1n}  \\
   0      & u_{22} & u_{23} & ... & b_{2n}  \\
   ...    & ...    & ...    & ... & ...     \\
   0      & 0      & ...    & ... & u_{nn}  \\
  \end{array} } \right]
$
  
Si la matriz A es invertible, es decir, tiene inversa, las matrices L y U son únicas.  

¿Qué utilidad tiene?   
* Resolución de sistemas de ecuaciones  
* Cálculo de la matriz inversa: A<sup>-1</sup>=U<sup>-1</sup> L<sup>-1</sup>  



<div class="alert alert-success">
    <b>Considerando la siguiente matriz $C$, realiza la factorización LU</b><br><br>

<center>$C = \left[ {\begin{array}{cc}
   2 & 1 & 1\\
   1 & 2 & 1\\
   1 & 1 & 2\\
  \end{array} } \right]$</center>

In [62]:
from scipy import linalg # from scipy import NOMBRE_FUNCION

C = np.array([[2, 1, 1],
              [1, 2, 1],
              [1, 1, 2]])

_, l, u = linalg.lu(C)

In [63]:
l

array([[1.        , 0.        , 0.        ],
       [0.5       , 1.        , 0.        ],
       [0.5       , 0.33333333, 1.        ]])

In [64]:
u

array([[2.        , 1.        , 1.        ],
       [0.        , 1.5       , 0.5       ],
       [0.        , 0.        , 1.33333333]])

Podemos comprobarlo realizando el producto matricial de $L$ y $U$:

In [65]:
np.dot(l, u)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [66]:
C

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

### 5.9.1- Pasos para descomponer un sistema de ecuaciones utilizando la factorización LU

1. Obtener la matriz triangular inferior $L$ y la matriz triangular superior $U$.  
2. Resolver $Ly = B$ (para encontrar y).  
3. El resultado del paso anterior se guarda en una matriz nueva de nombre "y".  
4. Realizar $Ux = y$ (para encontrar x).  
5. El resultado del paso anterior se almacena en una matriz nueva llamada "x", la cual da los valores correspondientes a las incógnitas de la ecuación.  

<div class="alert alert-success">
    <b>Vamos a encontrar las soluciones del sistema (usando la factorización LU):</b><br><br>
    
<center>$\left\{
       \begin{array}{ll}
           4x-2y-z=9  \\
           5x+y-z=7   \\
           x+2y-4z=12
       \end{array}
     \right.$</center>
</div><br><br>

Este sistema puede ser escrito como: 
<center>$\left(
\begin{array}{ccc|c}
4 & -2 & -1 & 9 \\
5 & 1  & -1 & 7 \\
1 & 2  & -4 & 12\\
\end{array}
\right)$</center><br>

donde: </style>    
<center>A= $\left(
\begin{array}{ll}
4 & -2 & -1 \\
5 & 1  & -1 \\
1 & 2  & -4 \\
\end{array}
\right)$</center><br>

y B es igual a:
<center>B= $\left(
\begin{array}{ll}
9 \\
7 \\
12\\
\end{array}
\right)$</center>

In [ ]:
#Ax = B # linear_system_solve()

Primero calculamos las matrices $L$ y $U$

In [91]:
A = np.array([[4, -2, -1],
              [5, 1, -1],
              [1, 2, -4]])

_, L, U = linalg.lu(A)
print(L)
print(U)

[[ 1.          0.          0.        ]
 [ 0.8         1.          0.        ]
 [ 0.2        -0.64285714  1.        ]]
[[ 5.          1.         -1.        ]
 [ 0.         -2.8        -0.2       ]
 [ 0.          0.         -3.92857143]]


El siguiente paso es resolver $Ly=B$ y guardarlo en la variable $y$:

In [92]:
B = np.array([[9],
              [7],
              [12]])

L_B = np.append(L, B, axis=1)
L_B

array([[ 1.        ,  0.        ,  0.        ,  9.        ],
       [ 0.8       ,  1.        ,  0.        ,  7.        ],
       [ 0.2       , -0.64285714,  1.        , 12.        ]])

Ahora resolvemos este sistema lineal:

In [100]:
from sympy import Matrix, solve_linear_system
from sympy.abc import x, y, z

L_B = Matrix(L_B)

y = solve_linear_system(L_B, x, y, z)
y

{x: 9.00000000000000, y: -0.200000000000000, z: 10.0714285714286}

Ahora resolvemos $Ux=y$ y lo guardamos en la variable $x$:

In [104]:
y_res = list(y.values())
y_array = np.array(y_res)
print(y_array.shape)
y_reshape = y_array.reshape(3, 1)
print(y_reshape.shape)

(3,)
(3, 1)


In [106]:
y_array

array([9.00000000000000, -0.200000000000000, 10.0714285714286],
      dtype=object)

In [105]:
y_reshape

array([[9.00000000000000],
       [-0.200000000000000],
       [10.0714285714286]], dtype=object)

In [ ]:
# (3x3) (3x1)

In [94]:
y_res = list(y.values())
y_array = np.array([y_res])
print(y_array)
print(y_array.shape)

# Reshape y_array to (3, 1)
y_reshape = y_array.reshape(3, 1)

y = Matrix(y_reshape)
U_Y = np.append(U, y, axis=1)
print(U_Y)

[[9.00000000000000 -0.200000000000000 10.0714285714286]]
(1, 3)
[[5.0 1.0 -1.0 9.00000000000000]
 [0.0 -2.8 -0.19999999999999996 -0.200000000000000]
 [0.0 0.0 -3.9285714285714284 10.0714285714286]]


Por último, resolvemos dicho sistema:

In [97]:
print(U_Y.shape)

(3, 4)


In [98]:
from sympy.abc import x, y, z

X = solve_linear_system(Matrix(U_Y), x, y, z)
X

{x: 1.23636363636364, y: 0.254545454545455, z: -2.56363636363636}