# Tensores

## 10.1 - ¿Qué son los tensores?


Un **tensor** es una generalización de vectores y matrices y se entiende fácilmente como una matriz multidimensional. A partir de esta definición podemos extrapolar que: 

- Un vector es un tensor unidimensional o de primer orden
- Una matriz es un tensor bidimensional o de segundo orden.  

<img src="Images/tensores.png" width=40%/>

La notación tensorial es muy parecida a la notación matricial con una letra mayúscula que representa un tensor y letras minúsculas con enteros subíndices que representan valores escalares dentro del tensor.  

$
 T =
  \left( {\begin{array}{cc}
   t111, t121, t131 \\  
   t211, t221, t231 \\  
   t311, t321, t331 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   t112, t122, t132 \\  
   t212, t222, t232 \\  
   t312, t322, t332 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   t113, t123, t133 \\  
   t213, t223, t233 \\  
   t313, t323, t333 \\  
  \end{array} } \right) 
$  

Muchas de las operaciones que se pueden realizar con escalares, vectores y matrices se pueden reformular para que se realicen con tensores.  

Como herramienta, los tensores y el álgebra tensorial se usan ampliamente en los campos de la física y la ingeniería. Al igual que los vectores y matrices, los tensores se pueden representar en Python usando la matriz N-dimensional (ndarray).  

Un tensor se puede definir como una lista de listas.

<div class="alert alert-success">
    Un tensor de 3x3x3 en Python<br>
    Primero definimos filas, luego una lista de filas apiladas como columnas, luego una lista de columnas apiladas como niveles en un cubo.
</div> 

         

In [1]:
import numpy as np

T = np.array([[[1,2,3], [4,5,6], [7,8,9]], 
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]])

print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


Podemos acceder a sus valores:

In [2]:
T[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
T[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [5]:
T[0][1].shape

(3,)

In [6]:
T[0][1][2]

6

## 10.2 - Suma de tensores

La adición de dos tensores con las mismas dimensiones produce un nuevo tensor con las mismas dimensiones donde cada valor escalar es la adición de los escalares en los tensores padres.  


$
  A =
  \left( {\begin{array}{cc}
   a111, a121, a131 \\  
   a211, a221, a231 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a112, a122, a132 \\  
   a112, a122, a132 \\  
  \end{array} } \right)
$   

$
  B =
  \left( {\begin{array}{cc}
   b111, b121, t131 \\  
   b211, t221, t231 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   b112, b122, b132 \\  
   b112, b122, b132 \\  
  \end{array} } \right)
$  

$
  A + B =
  \left( {\begin{array}{cc}
   a111 + b111, a121 + b121, a131 + b131 \\  
   a211 + b211, a221 + b221, a231 + b231 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a112 + b112, a122 + b122, a132 + b132 \\  
   a112 + b112, a122 + b122, a132 + b132 \\  
  \end{array} } \right) , 
$   

En `numpy`, podemos agregar tensores directamente agregando matrices.

In [8]:
A = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]
             ])

B = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]])

C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [10]:
A = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]
             ])

B = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]])

C = B - A
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


## 10.3 - Producto de tensores Hadamard

La multiplicación por elementos de un tensor con otro tensor con las mismas dimensiones da como resultado un nuevo tensor con las mismas dimensiones donde cada valor escalar es la multiplicación por elementos de los escalares en los tensores padres.  

La operación se conoce como Producto Hadamard para diferenciarla de la multiplicación tensorial. Aquí, utilizaremos el operador "o" para indicar el funcionamiento del producto Hadamard entre tensores.  

$
  A =
  \left( {\begin{array}{cc}
   a111, a121, a131 \\  
   a211, a221, a231 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a112, a122, a132 \\  
   a112, a122, a132 \\  
  \end{array} } \right) 
$   

$
  B =
  \left( {\begin{array}{cc}
   b111, b121, t131 \\  
   b211, t221, t231 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   b112, b122, b132 \\  
   b112, b122, b132 \\  
  \end{array} } \right)
$  

$
  A o B =
  \left( {\begin{array}{cc}
   a111 * b111, a121 * b121, a131 * b131 \\  
   a211 * b211, a221 * b221, a231 * b231 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a112 * b112, a122 * b122, a132 * b132 \\  
   a112 * b112, a122 * b122, a132 * b132 \\  
  \end{array} } \right) , 
$  

In [1]:
#np.dot(A, B)

In [12]:
A = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]
             ])

B = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]])

C = A * B
C

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[121, 144, 169],
        [196, 225, 256],
        [289, 324, 361]],

       [[441, 484, 529],
        [576, 625, 676],
        [729, 784, 841]]])

Si cambiamos las dimensiones de uno de los tensores

In [13]:
A = np.array([[[1,2,3],    [4,5,6]],
              [[11,12,13], [14,15,16]],
              [[21,22,23], [24,25,26]]
             ])

B = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]])

print("A shape: ", A.shape)
print("B shape: ", B.shape)
print("C shape: ", C.shape)

A shape:  (3, 2, 3)
B shape:  (3, 3, 3)
C shape:  (3, 3, 3)


In [14]:
C = A * B
C

ValueError: operands could not be broadcast together with shapes (3,2,3) (3,3,3) 

## 10.4 - División de tensores

$
  A =
  \left( {\begin{array}{cc}
   a111, a121, a131 \\  
   a211, a221, a231 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   a112, a122, a132 \\  
   a112, a122, a132 \\  
  \end{array} } \right) 
$   

$
  B =
  \left( {\begin{array}{cc}
   b111, b121, t131 \\  
   b211, t221, t231 \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   b112, b122, b132 \\  
   b112, b122, b132 \\  
  \end{array} } \right) 
$  

$
  A / B =
  \left( {\begin{array}{cc}
   \frac{a111}{b111}, \frac{a121}{b121}, \frac{a131}{b131} \\  
   \frac{a211}{b211}, \frac{a221}{b221}, \frac{a231}{b231} \\  
  \end{array} } \right) ,
  \left( {\begin{array}{cc}
   \frac{a112}{b112}, \frac{a122}{b122}, \frac{a132}{b132} \\  
   \frac{a112}{b112}, \frac{a122}{b122}, \frac{a132}{b132} \\  
  \end{array} } \right) , 
$

In [16]:
A = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]
             ])

B = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]])

C = A / B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [17]:
print(A.shape)
print(B.shape)
print(C.shape)

(3, 3, 3)
(3, 3, 3)
(3, 3, 3)


## 10.5 - Producto tensor

El operador del producto tensor a menudo se denota como un círculo con una pequeña x en el centro $\otimes$.

Dado un tensor $A$ con $q$ dimensiones y tensor $B$ con $r$ dimensiones, el producto de estos tensores será un nuevo tensor con $q + r$ dimensiones.

El producto tensor no se limita a tensores, sino que también se puede realizar en matrices y vectores, que pueden ser un buen lugar para practicar con el fin de desarrollar la intuición para dimensiones superiores.

### Producto tensor para vectores

$a = (a1, a2)$<br>
$b = (b1, b2)$<br>
$c = a \otimes b$<br>

$
  c =
  \left( {\begin{array}{cc}
   a1 * [b1, b2] \\  
   a2 * [b1, b2] \\  
  \end{array} } \right) =
  \left( {\begin{array}{cc}
   a1 * b1, a1 * b2 \\  
   a2 * b1, a2 * b2 \\  
  \end{array} } \right)  
$   

### Producto tensor para matrices

$ A =
  \left( {\begin{array}{cc}
   a11, a12 \\  
   a21, a22 \\  
  \end{array} } \right)
$  

$ B =
  \left( {\begin{array}{cc}
   b11, b12 \\  
   b21, b22 \\  
  \end{array} } \right)
$  

$C = A \otimes B$<br>
 
$ C =
  \left( {\begin{array}{cc}
   a11*\left( {\begin{array}{cc}
           b11, b12 \\  
           b21, b22 \\  
          \end{array} } \right), a12 *\left( {\begin{array}{cc}
           b11, b12 \\  
           b21, b22 \\  
          \end{array} } \right) \\  
   a21*\left( {\begin{array}{cc}
           b11, b12 \\  
           b21, b22 \\  
          \end{array} } \right), a22 *\left( {\begin{array}{cc}
           b11, b12 \\  
           b21, b22 \\  
          \end{array} } \right) \\ 
  \end{array} } \right) =
  \left( {\begin{array}{cc}
   a11 * b11, a11 * b12, a12 * b11, a12 * b12 \\  
   a11 * b21, a11 * b22, a12 * b21, a12 * b22 \\ 
   a21 * b11, a21 * b12, a22 * b11, a22 * b12 \\ 
   a21 * b21, a21 * b22, a22 * b21, a22 * b22 \\ 
  \end{array} } \right) 
$   

`Numpy` puede realizar el producto tensor usando la función `tensordot`. La función toma como argumentos **los dos tensores a multiplicar** y **el eje sobre el que se suman los productos**, llamada `sum reduction`. Para calcular el producto tensor, también llamado producto de punto tensor en `numpy`, el eje debe establecerse en 0.

In [19]:
A = np.array([1, 2])
B = np.array([3, 4])

C = np.tensordot(A, B, axes=0)

print(C)

[[3 4]
 [6 8]]


In [ ]:
# Igual a np.dot(A, B) pero para tensores

In [22]:
A = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]
             ])

B = np.array([[[1,2,3],    [4,5,6],    [7,8,9]],
              [[11,12,13], [14,15,16], [17,18,19]],
              [[21,22,23], [24,25,26], [27,28,29]]])

C = np.tensordot(A, B)
C.shape

(3, 3)

## 10.6 - Tensores con TensorFlow

Vamos a ver algunos pequeños ejemplos sobre tensores usando `tensorflow`

In [23]:
import tensorflow as tf
import numpy as np

In [ ]:
#!pip install tensorflow

Con `tf.constant()` generamos un escalar de tipo `int32`

In [24]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


Podemos crear un vector (1 axis):

In [25]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [26]:
rank_1_tensor.shape

TensorShape([3])

In [27]:
rank_1_tensor.dtype

tf.float32

Con 2 axis:

In [30]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

<img src="Images/tensors.png" width=80%/>

Con más axis:

In [31]:
rank_3_tensor = tf.constant([[[0, 1, 2, 3, 4],
                             [5, 6, 7, 8, 9]],
                            [[10, 11, 12, 13, 14],
                             [15, 16, 17, 18, 19]],
                            [[20, 21, 22, 23, 24],
                             [25, 26, 27, 28, 29]]])
rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

Hay muchas formas de visualizar un tensor con 3 axis:

<img src="Images/tensors_3axis.png" width=80%/>

Con `np.array()` podemos convertir un `tensor` a una variable de `numpy`

In [32]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [34]:
type(np.array(rank_2_tensor))

numpy.ndarray

In [35]:
np.array(rank_2_tensor).shape

(3, 2)

Podemos realizar operaciones básicas:

In [36]:
a = tf.constant([[1, 2],
                 [3, 4]])

b = tf.constant([[1, 1],
                 [1, 1]])

In [37]:
# Suma
print(tf.add(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [38]:
# Multiplicación - elemento a elemento a * b
print(tf.multiply(a, b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [39]:
# Multiplicación matricial np.dot(a, b)
print(tf.matmul(a, b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


O usando los siguientes operadores:

In [40]:
# Suma
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [41]:
# Multiplicación - elemento a elemento
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [42]:
# Multiplicación matricial
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]])>

Otro tipo de operaciones muy usadas son:

- `tf.reduce_max()` para encontrar el valor más grande
- `tf.argmax()` para encontrar el índice del valor más grande

In [43]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

print(tf.reduce_max(c))

tf.Tensor(10.0, shape=(), dtype=float32)


In [44]:
print(tf.argmax(c))

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [ ]:
# Pytorch, TensorFlow (Keras) - frameworks Deep Learning
# Pytorch - Facebook 
# TensorFlow - Google
# Keras (TensorFlow)